#!/usr/bin/env bash

# Label some initial data points.
echo "1
2
3
4
5
6
7
8
9
10
" | acton-label \
    --data tests/data/classification.txt \
    --label col20 -v > labels.pb

for (( epoch = 0; epoch < 10; epoch++ )); do
    echo Epoch $epoch
    acton-predict -v < labels.pb | acton-recommend -v | acton-label -v > labels_.pb
    mv labels_.pb labels.pb
done
