# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predictors.proto',
  package='acton.predictors',
  syntax='proto3',
  serialized_pb=_b('\n\x10predictors.proto\x12\x10\x61\x63ton.predictors\"\xd7\x01\n\x06Labels\x12;\n\x08instance\x18\x01 \x03(\x0b\x32).acton.predictors.Labels.LabelledInstance\x12\x13\n\x0bn_labellers\x18\x02 \x01(\x05\x12\x1a\n\x12n_label_dimensions\x18\x03 \x01(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x62_path\x18\x05 \x01(\t\x12\x10\n\x08\x64\x62_class\x18\x06 \x01(\t\x1a-\n\x10LabelledInstance\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x03(\x01\"\xf5\x01\n\x0bPredictions\x12<\n\nprediction\x18\x01 \x03(\x0b\x32(.acton.predictors.Predictions.Prediction\x12\x14\n\x0cn_predictors\x18\x02 \x01(\x05\x12\x1f\n\x17n_prediction_dimensions\x18\x03 \x01(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x11\n\tpredictor\x18\x05 \x01(\t\x12\x0f\n\x07\x64\x62_path\x18\x06 \x01(\t\x12\x10\n\x08\x64\x62_class\x18\x07 \x01(\t\x1a,\n\nPrediction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x03(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LABELS_LABELLEDINSTANCE = _descriptor.Descriptor(
  name='LabelledInstance',
  full_name='acton.predictors.Labels.LabelledInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='acton.predictors.Labels.LabelledInstance.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='acton.predictors.Labels.LabelledInstance.label', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=254,
)

_LABELS = _descriptor.Descriptor(
  name='Labels',
  full_name='acton.predictors.Labels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='acton.predictors.Labels.instance', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_labellers', full_name='acton.predictors.Labels.n_labellers', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_label_dimensions', full_name='acton.predictors.Labels.n_label_dimensions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='acton.predictors.Labels.dtype', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='db_path', full_name='acton.predictors.Labels.db_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='db_class', full_name='acton.predictors.Labels.db_class', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LABELS_LABELLEDINSTANCE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=254,
)


_PREDICTIONS_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='acton.predictors.Predictions.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='acton.predictors.Predictions.Prediction.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='acton.predictors.Predictions.Prediction.prediction', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=502,
)

_PREDICTIONS = _descriptor.Descriptor(
  name='Predictions',
  full_name='acton.predictors.Predictions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prediction', full_name='acton.predictors.Predictions.prediction', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_predictors', full_name='acton.predictors.Predictions.n_predictors', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_prediction_dimensions', full_name='acton.predictors.Predictions.n_prediction_dimensions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='acton.predictors.Predictions.dtype', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictor', full_name='acton.predictors.Predictions.predictor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='db_path', full_name='acton.predictors.Predictions.db_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='db_class', full_name='acton.predictors.Predictions.db_class', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTIONS_PREDICTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=502,
)

_LABELS_LABELLEDINSTANCE.containing_type = _LABELS
_LABELS.fields_by_name['instance'].message_type = _LABELS_LABELLEDINSTANCE
_PREDICTIONS_PREDICTION.containing_type = _PREDICTIONS
_PREDICTIONS.fields_by_name['prediction'].message_type = _PREDICTIONS_PREDICTION
DESCRIPTOR.message_types_by_name['Labels'] = _LABELS
DESCRIPTOR.message_types_by_name['Predictions'] = _PREDICTIONS

Labels = _reflection.GeneratedProtocolMessageType('Labels', (_message.Message,), dict(

  LabelledInstance = _reflection.GeneratedProtocolMessageType('LabelledInstance', (_message.Message,), dict(
    DESCRIPTOR = _LABELS_LABELLEDINSTANCE,
    __module__ = 'predictors_pb2'
    # @@protoc_insertion_point(class_scope:acton.predictors.Labels.LabelledInstance)
    ))
  ,
  DESCRIPTOR = _LABELS,
  __module__ = 'predictors_pb2'
  # @@protoc_insertion_point(class_scope:acton.predictors.Labels)
  ))
_sym_db.RegisterMessage(Labels)
_sym_db.RegisterMessage(Labels.LabelledInstance)

Predictions = _reflection.GeneratedProtocolMessageType('Predictions', (_message.Message,), dict(

  Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), dict(
    DESCRIPTOR = _PREDICTIONS_PREDICTION,
    __module__ = 'predictors_pb2'
    # @@protoc_insertion_point(class_scope:acton.predictors.Predictions.Prediction)
    ))
  ,
  DESCRIPTOR = _PREDICTIONS,
  __module__ = 'predictors_pb2'
  # @@protoc_insertion_point(class_scope:acton.predictors.Predictions)
  ))
_sym_db.RegisterMessage(Predictions)
_sym_db.RegisterMessage(Predictions.Prediction)


# @@protoc_insertion_point(module_scope)
